name: Build and Deploy Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload site to Azure Storage
        run: echo "Uploading site..."
