name: Node CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npm install 

    - name: Build site
      run: npm run build
