name: Build and Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build
        env:
          REPOSITORY_NAME_GHOST: ${{ secrets.REPOSITORY_NAME_GHOST }}
          API_KEY_GHOST: ${{ secrets.API_KEY_GHOST }}
          REPOSITORY_NAME_PRISMIC: ${{ secrets.REPOSITORY_NAME_PRISMIC }}
          API_KEY_PRISMIC: ${{ secrets.API_KEY_PRISMIC }}

      - name: Upload site to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "public"
